version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container-trading
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trading
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
      TZ: UTC
    ports:
      - "3308:3306"
    volumes:
      - mysql_trading_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kafka-network

  app:
    build:
      context: .
    container_name: springboot-app-trading
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5456:5456"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/trading?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: spring
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    networks:
      - kafka-network

volumes:
  mysql_trading_data:

networks:
  kafka-network:
    external: true
